version: '3'
services:
  zookeeper:
    image: zookeeper:3.6.3
    restart: always
    container_name: zookeeper
    ports:
      - '2181:2181'
    volumes:
      - zookeeper_data:/data
    networks:
      - n5network

  kafka:
    image: confluentinc/cp-kafka:6.2.0
    restart: always
    container_name: kafka
    depends_on:
      - zookeeper
    ports:
      - '9092:9092'
    environment:
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
      - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://127.0.0.1:9092
      - KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR=1
    volumes:
      - kafka_data:/var/lib/kafka/data
    networks:
      - n5network

  kibana:
    image: docker.elastic.co/kibana/kibana:7.15.1
    restart: always
    container_name: kibana
    ports:
      - '5601:5601'
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
    networks:
      - n5network

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.15.1
    restart: always
    container_name: elasticsearch
    ports:
      - '9200:9200'
      - '9300:9300'
    environment:
      - discovery.type=single-node
    volumes:
      - elasticsearch_data:/usr/share/elasticsearch/data
    networks:
      - n5network

  sqlserver:
    image: mcr.microsoft.com/mssql/server:2019-latest
    restart: always
    container_name: sqlserver
    ports:
      - '14433:1433'
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=N5Ch4ll3ng3*
    volumes:
      - sqlserver_data:/var/opt/mssql
    networks:
      - n5network

  n5app:
    build:
      context: .
      dockerfile: N5.Challenge.API/Dockerfile
    ports:
      - 80:80
    depends_on:
      - sqlserver
      - elasticsearch
      - kafka
    networks:
      - n5network

volumes:
  zookeeper_data:
    driver: local
  kafka_data:
    driver: local
  elasticsearch_data:
    driver: local
  sqlserver_data:
    driver: local

networks:
  n5network: