version: '3'
services:
  zookeeper:
    image: bitnami/zookeeper
    restart: always
    container_name: zookeeper
    ports:
      - '2181:2181'
    volumes:
      - "zookeeper_data:/bitnami"
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
      - ZOOKEEPER_CLIENT_PORT=2181
      - ZOOKEEPER_TICK_TIME=2000
    networks:
      - n5network
  kafka:
    image: bitnami/kafka:2.8.1-debian-10-r186
    restart: always
    container_name: kafka
    depends_on:
      - zookeeper
    ports:
      - '9092:9092'
    environment:
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
      - ALLOW_PLAINTEXT_LISTENER=yes
      - KAFKA_LISTENERS=PLAINTEXT://:9092
      - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://kafka:9092
    volumes:
      - "kafka_data:/bitnami"
    networks:
      - n5network
  kibana:
    image: docker.elastic.co/kibana/kibana:7.15.1
    restart: always
    container_name: kibana
    ports:
      - '5601:5601'
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
    networks:
      - n5network
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.15.1
    restart: always
    container_name: elasticsearch
    ports:
      - '9200:9200'
      - '9300:9300'
    environment:
      - discovery.type=single-node
    volumes:
      - elasticsearch_data:/usr/share/elasticsearch/data
    networks:
      - n5network

  sql-server:
    image: mcr.microsoft.com/mssql/server:2019-latest
    restart: always
    container_name: sql-server
    ports:
      - '1433:1433'
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=N5Ch4ll3ng3*
    volumes:
      - sqlserver_data:/var/opt/mssql
    networks:
      - n5network

  n5app:
    restart: always
    container_name: n5app
    build:
      context: .
      dockerfile: N5.Challenge.API/Dockerfile
    ports:
      - 8080:80
    depends_on:
      - sql-server
      - elasticsearch
      - kafka
    networks:
      - n5network

volumes:
  zookeeper_data:
    driver: local
  kafka_data:
    driver: local
  elasticsearch_data:
    driver: local
  sqlserver_data:
    driver: local

networks:
  n5network:
    name: n5networkNetwork
    driver: bridge